Crated an example page for `Mail`
yamada-ui/yamada-docs pull request #247
Opened 2024-03-31 08:36 UTC by umaidashi

Closes #204 

## Description

> Crated an example page for `Mail`

## Is this a breaking change (Yes/No):

No

## Additional Information

wip

2024-04-02 07:16 UTC, 108yen requested changes
- Do not use `&&` outside of conditional statements as this may cause bugs.
- Need to be responsive.

2024-04-02 07:16 UTC, 108yen commented on pages/examples/mail/index.tsx
> +  const [selectedMail, setSelectedMail] = useState<MailType>(mails[0])
Implement using `useRef` in the same way as `Playground`.

2024-04-02 07:16 UTC, 108yen commented on pages/examples/mail/index.tsx
> +  )
Used only with `MailSidebar`, is it needed here?

2024-04-02 15:19 UTC, umaidashi commented on pages/examples/mail/index.tsx
> +  const [selectedMail, setSelectedMail] = useState<MailType>(mails[0])
I don't understand `useRef` in detail, but in this case I used `useState` because I need to re-render the email in the Detail component
I am not sure why you would use `useRef`, since even if you use `useRef`, you still need to use `useState` in one of the components.

2024-04-03 01:27 UTC, 108yen commented on pages/examples/mail/index.tsx
> +  const [selectedMail, setSelectedMail] = useState<MailType>(mails[0])
@umaidashi 
With `useState` the whole thing is re-rendered, but with `useRef` it is possible to re-render only the components you need.
In the following, changes on the `Prompt` side are propagated to the `Menu` and only the `Menu` is re-rendered.
https://github.com/yamada-ui/yamada-docs/blob/26c9bc630f8ce2a3b9f47f385aa058ef32f729fe/pages/examples/playground/editor/index.tsx#L15-L37

2024-04-06 22:51 UTC, hirotomoyamada approved these changes

2024-04-06 22:52 UTC, merged